spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_train
    username: hao
    password: 1122

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        use_sql_comments: true

  redis:
    database: 0                   # Redis数据库索引（默认为0 redis有16个库）
    host: 127.0.0.1
    port: 6379
    password:                     # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8             # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1              # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8               # 连接池中的最大空闲连接
        min-idle: 0               # 连接池中的最小空闲连接
    timeout: 0                    # 连接超时时间（毫秒）

